version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: cmr-es-elastic
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ELASTIC_PASSWORD=kibana
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${PWD}/data/elastic:/usr/share/elasticsearch/data
    ports:
      - 9209:9200
    networks:
      - cmr-es-net

volumes:
  data:
    driver: local
  logs:
    driver: local

networks:
  cmr-es-net:
